name: .NET CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./backend/FinancialRisk.sln

    - name: Build
      run: dotnet build ./backend/FinancialRisk.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test ./backend/FinancialRisk.sln --no-build --verbosity normal
