name: .NET CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./backend/FinancialRisk.sln

    - name: Build
      run: dotnet build ./backend/FinancialRisk.sln --no-restore --configuration Release

    - name: Test
      # Exclude integration tests due to server configuration issues
      # Integration tests will be re-enabled once the WebApplicationFactory setup is fixed
      run: dotnet test ./backend/FinancialRisk.sln --no-build --configuration Release --verbosity normal --filter "Category!=Integration"
